version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/opt/app/mcache
    environment:
      PORT: 4567
      HOST: 0.0.0.0
      AUTH_ENABLED: true
      AUTH_USER: admin
      AUTH_PASSWORD: adminpass
      PERSIST: true
    ports:
    - "4567:4567"